### ISSUE TITLE
Add Accessibility to "Principles of development"

### ISSUE THREAD

**Issue by dimarconicola** [dexlab-io/Organization#1]
Definition of web accessibility (W3C)

"The Web is fundamentally designed to work for all people, whatever their hardware, software, language, culture, location, or physical or mental ability. When the Web meets this goal, it is accessible to people with a diverse range of hearing, movement, sight, and cognitive ability.

Thus the impact of disability is radically changed on the Web because the Web removes barriers to communication and interaction that many people face in the physical world. However, when websites, web technologies, or web tools are badly designed, they can create barriers that exclude people from using the Web.

It is essential that the Web be accessible in order to provide equal access and equal opportunity to people with diverse abilities. Indeed, the UN Convention on the Rights of Persons with Disabilities recognizes access to information and communications technologies, including the Web, as a basic human right."

According to this, shouldn't we consider access to crypto as a basic human right as well?

**Comment by Alexintosh** [comment]
I definitely agree with this, can you formalise the changes in `Vision.md` as  a pull request?

Thanks.
